// <auto-generated />
using System;
using GerenciadorProcessos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciadorProcessos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810141317_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorProcessos.Domain.Entities.Andamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProcessoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Andamentos");
                });

            modelBuilder.Entity("GerenciadorProcessos.Domain.Entities.Parte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProcessoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoParte")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Partes");
                });

            modelBuilder.Entity("GerenciadorProcessos.Domain.Entities.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroProcesso")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NumeroProcesso")
                        .IsUnique();

                    b.ToTable("Processos");
                });

            modelBuilder.Entity("GerenciadorProcessos.Domain.Entities.Andamento", b =>
                {
                    b.HasOne("GerenciadorProcessos.Domain.Entities.Processo", "Processo")
                        .WithMany("Andamentos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("GerenciadorProcessos.Domain.Entities.Parte", b =>
                {
                    b.HasOne("GerenciadorProcessos.Domain.Entities.Processo", "Processo")
                        .WithMany("Partes")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("GerenciadorProcessos.Domain.Entities.Processo", b =>
                {
                    b.Navigation("Andamentos");

                    b.Navigation("Partes");
                });
#pragma warning restore 612, 618
        }
    }
}
